# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: //minghaohu.com
date_format: "ordinal"
title: 胡明昊的个人网站
subtitle: "胡明昊"
logo:
description: "分享我的知识，见闻，生活和理想"
keywords: 胡明昊, Minghao Hu, minghao, Minghao23, hmh
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 4

# ---------------- #
#      Author      #
# ---------------- #
author: Minghao Hu
organization: www.minghaohu.com
organization_url: http://www.minghaohu.com
github_username: Minghao23
location: Beijing, China
email: hu_minghao@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 主页

  -
    href: /tech/
    label: 技术

  -
    href: /life/
    label: 生活

  -
    href: /wiki/
    label: 维基

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Minghao23/minghao23.github.io

# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: gitalk
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Minghao23
    repo: Minghao23.github.io
    clientID: 5e13dcbaa5700878625d
    clientSecret: 69a24f8d55550e22fd2faa56a26c4aa9c4e50420
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
